/* Copy and translations. Keep both language dictionaries in sync. */
const NCIT_COPY = {
  "zh": {
    "skip": "跳转到主要内容",
    "mainNav": "主导航",
    "navSolution": "解决方案",
    "navTech": "核心技术",
    "navDemo": "项目演示",
    "navTeam": "关于团队",
    "contactUs": "合作咨询",
    "openMenu": "打开导航",
    "mobileNav": "移动端导航",
    "heroAlt": "多机械臂围绕共享工位进行框架装配的概念场景",
    "heroEyebrow": "星云协智 · 多机械臂协同智能",
    "heroLine1": "让多臂协作，",
    "heroLine2": "拥有共同的智能。",
    "heroDesc": "以共享世界模型连接感知、决策与行动，让多只机械臂理解同一个世界，协同完成复杂制造任务。",
    "explore": "探索解决方案",
    "watchDemo": "观看协作演示",
    "heroTag1": "共享世界模型",
    "heroTag2": "三 / 四臂协作",
    "heroTag3": "柔性制造",
    "conceptCaption": "多臂协作工位 · 概念示意",
    "researchOrigin": "源于前沿研究，走向真实制造",
    "affiliation": "香港科技大学（广州）科技初创项目",
    "location": "广州 · 南沙",
    "solutionEyebrow": "01 — 为复杂协作而生",
    "solutionLine1": "从各自执行，",
    "solutionLine2": "到协同完成。",
    "solutionDesc": "非标制造的挑战，不止是让一只机械臂动起来。共同持物、对齐、紧固与恢复，需要整个系统拥有一致的理解与行动。",
    "challenge1Title": "强耦合，也能默契配合",
    "challenge1Desc": "共享对象状态与装配关系，让搬运、支撑与工具作业在同一节奏下协同。",
    "challenge1Tag": "共同持物 · 协作装配",
    "challenge2Title": "换一种任务，延续能力",
    "challenge2Desc": "面向多品种、小批量生产，通过任务技能与数据复用，减少反复示教的负担。",
    "challenge2Tag": "任务复用 · 柔性换型",
    "challenge3Title": "理解异常，重新协同",
    "challenge3Desc": "将错位、滑移与遮挡纳入状态判断，通过主动观察与任务接替恢复协作。",
    "challenge3Tag": "主动观察 · 异常恢复",
    "challenge4Title": "不同本体，同一协作层",
    "challenge4Desc": "以统一接口连接不同机械臂，让品牌、控制频率和时延差异得到系统化适配。",
    "challenge4Tag": "跨本体适配 · 可扩展架构",
    "techEyebrow": "02 — 协同智能的核心",
    "techLine1": "一个世界模型。",
    "techLine2": "连接每一次协作。",
    "techDesc": "NCIT 构建位于机器人本体之上的协同智能层，将共享理解、联合预测与协作执行连接成闭环。",
    "diagramAlt": "共享世界模型连接供料、支撑、紧固和恢复四个协作角色",
    "architectureTag": "系统架构",
    "diagramInput": "多视角观测 · 对象状态 · 任务上下文",
    "worldModel": "共享世界模型",
    "worldModelSub": "理解状态 · 预测协作 · 更新决策",
    "arm1": "供料搬运",
    "arm2": "支撑对齐",
    "arm3": "连接紧固",
    "arm4": "弹性支撑",
    "feedback": "执行反馈与失败数据，持续更新协作能力",
    "techTabs": "技术能力",
    "techTab1": "共享感知",
    "techTab2": "联合预测",
    "techTab3": "异常恢复",
    "techTab4": "跨本体适配",
    "platformFoot1": "面向三臂到四臂的可扩展协作",
    "platformFoot2": "连接数据、模型、本体与场景",
    "applicationEyebrow": "03 — 从具体工位开始",
    "applicationLine1": "一副框架，",
    "applicationLine2": "开启柔性制造的可能。",
    "applicationDesc": "以铝型材定制框架组装为首个场景，围绕共同搬运、支撑对齐和工具紧固，构建三臂、四臂协作闭环。",
    "sceneTabs": "查看场景",
    "labTab": "实验室真机",
    "simTab": "协作仿真",
    "firstScenario": "首个应用场景 / 铝型材框架装配",
    "step1Title": "供料与主搬运",
    "step1Desc": "抓取型材，送入共享装配区域。",
    "step2Title": "支撑与精确对齐",
    "step2Desc": "稳定保持框架，协调端面与角度。",
    "step3Title": "连接与工具紧固",
    "step3Desc": "放置连接件，协同完成工具作业。",
    "step4Title": "弹性支撑与恢复",
    "step4Desc": "主动观察状态变化，调整角色与动作。",
    "applicationNote": "从可量化的装配任务出发，沉淀可复用的技能、数据与交付能力。",
    "directionsLabel": "拓展应用方向",
    "direction1": "线束协同布线",
    "direction2": "精密检测与上料",
    "direction3": "柔性包装",
    "direction4": "大型构件协作",
    "demoEyebrow": "04 — 看见协作发生",
    "demoTitle": "不同角色，同一个目标。",
    "demoDesc": "四臂协作组装铝型材框架。观看模拟环境中的协作流程，了解多臂任务如何衔接。",
    "simulationBadge": "仿真演示",
    "videoAlt": "四机械臂协作组装铝型材框架仿真视频",
    "videoFallback": "您的浏览器不支持视频播放，请下载演示视频观看。",
    "videoCaption": "四臂协作 · 铝型材框架组装 · 模拟环境",
    "downloadVideo": "下载演示视频",
    "researchTitle": "建立在持续研发之上",
    "researchDesc": "从仿真训练、通信方法到真机数据采集，连接算法探索与系统实践。",
    "researchAlt1": "四机械臂协作装配的模拟环境",
    "research1Title": "共享世界模型探索",
    "research1Desc": "多臂仿真环境中的状态建模、联合预测与协作方案验证。",
    "researchAlt2": "多机械臂协作仿真训练的连续画面",
    "research2Title": "多臂通信与策略学习",
    "research2Desc": "围绕协作任务，开展通信方法与视觉—语言—动作模型的仿真训练。",
    "researchAlt3": "真实机械臂在桌面水果分类任务中采集数据",
    "research3Title": "真机数据与模型微调",
    "research3Desc": "双臂家居协作任务的真机与仿真数据采集，以及模型微调实践。",
    "roadmapEyebrow": "05 — 从技术到产品",
    "roadmapTitle": "每一步，走向真实交付。",
    "roadmapDesc": "以 24 个月研发路线连接最小真机闭环、模型迭代、跨本体适配与客户工位验证。",
    "roadmapTime1": "01—03 个月",
    "roadmap1Title": "三臂最小闭环",
    "roadmap1Desc": "完成搬运、保持、对齐与连接的限定真机流程，建立统一数据接口。",
    "roadmapTime2": "04—09 个月",
    "roadmap2Title": "共享世界模型 V1",
    "roadmap2Desc": "建立对象与装配关系状态、异常日志和联合动作预测，完成基线比较。",
    "roadmapTime3": "10—15 个月",
    "roadmap3Title": "四臂与跨本体 V2",
    "roadmap3Desc": "扩展四臂共同持物、支撑与工具作业，适配第二类机械臂接口。",
    "roadmapTime4": "16—24 个月",
    "roadmap4Title": "客户验证与工位复制",
    "roadmap4Desc": "推进边缘部署、连续运行验证，以及第二工位复制与客户验收。",
    "targetsLabel": "研发与验收目标",
    "targetsNote": "24 个月阶段规划",
    "target1": "协同机械臂",
    "target2": "类机械臂接口",
    "target3": "连续运行验证",
    "target4": "付费 PoC 或订单",
    "teamEyebrow": "06 — 跨越研究与产业",
    "teamLine1": "共同的方向，",
    "teamLine2": "互补的力量。",
    "teamDesc": "汇聚多智能体算法、技术产品化与机器人系统工程经验，让科研能力与交付能力在同一个团队相遇。",
    "name1": "苏宁馨",
    "role1": "项目负责人 · 首席科学家",
    "bio1": "香港科技大学（广州）物联网与机器人学域联聘助理教授，多伦多大学博士。负责多智能体世界模型研发与科研组织。",
    "expertise1": "多智能体算法 / 校企研发",
    "name2": "刘帅军",
    "role2": "拟任 CEO · 技术产品化",
    "bio2": "博士生创业者、ayaMaa 联合创始人，曾负责品牌出海业务。推进技术产品化、客户需求定义与公司运营。",
    "expertise2": "产品化 / 客户与经营",
    "name3": "杨庆凯",
    "role3": "工程与交付负责人",
    "bio3": "锐动新创 CEO，曾任乐聚机器人夸父系列核心工程师，具有人形与重载四足机器人研发经验。负责硬件、系统工程与现场交付。",
    "expertise3": "机器人系统 / 工程交付",
    "collabEyebrow": "07 — 让能力进入生产",
    "collabTitle": "与你一起，把协作带到现场。",
    "collabDesc": "面向制造企业、机械臂厂商与系统集成商，提供协同智能层，与合作伙伴共同完成从场景定义到部署复制的每一步。",
    "cooperation1Title": "场景共创 · 付费 PoC",
    "cooperation1Desc": "梳理物料、工序与协作需求，明确任务边界、成功率和验收标准，验证最小闭环。",
    "cooperation2Title": "工位部署 · 系统适配",
    "cooperation2Desc": "围绕真实工位完成算法适配、模型训练、回归验证与现场验收。",
    "cooperation3Title": "持续服务 · 规模复制",
    "cooperation3Desc": "通过年度授权、版本升级、任务包与 OEM 合作，复用数据和技能，拓展更多工位。",
    "contactEyebrow": "LET’S BUILD TOGETHER",
    "contactLine1": "下一次协作，",
    "contactLine2": "从这里开始。",
    "contactDesc": "如果你的生产现场，也有一个需要多臂共同完成的挑战，欢迎与我们交流。",
    "contactLabel": "项目与研发合作",
    "contactPerson": "苏宁馨 · 项目负责人",
    "emailUs": "邮件联系",
    "visitLab": "了解 NEBULIS Lab",
    "footerBrand": "星云协智 · NCIT",
    "footerMission": "让多臂协作，拥有共同的智能。",
    "footerStatus": "香港科技大学（广州）科技初创项目 · 拟落地广州南沙",
    "backTop": "返回顶部"
  },
  "en": {
    "skip": "Skip to main content",
    "mainNav": "Main navigation",
    "navSolution": "Solutions",
    "navTech": "Technology",
    "navDemo": "Demo",
    "navTeam": "Our team",
    "contactUs": "Let’s collaborate",
    "openMenu": "Open navigation",
    "mobileNav": "Mobile navigation",
    "heroAlt": "Concept illustration of multiple robot arms assembling a frame around a shared workcell",
    "heroEyebrow": "NCIT · COLLABORATIVE ROBOTIC INTELLIGENCE",
    "heroLine1": "Many arms.",
    "heroLine2": "One shared intelligence.",
    "heroDesc": "A shared world model connects perception, decisions and action—so multiple robot arms understand the same world and solve complex manufacturing tasks together.",
    "explore": "Explore our approach",
    "watchDemo": "Watch the demo",
    "heroTag1": "Shared world models",
    "heroTag2": "3 / 4-arm collaboration",
    "heroTag3": "Flexible manufacturing",
    "conceptCaption": "Collaborative workcell · Concept illustration",
    "researchOrigin": "From frontier research to real manufacturing",
    "affiliation": "A technology startup project from HKUST(GZ)",
    "location": "Nansha · Guangzhou",
    "solutionEyebrow": "01 — BUILT FOR COMPLEX COLLABORATION",
    "solutionLine1": "Beyond individual motion.",
    "solutionLine2": "Towards collective action.",
    "solutionDesc": "High-mix, low-volume manufacturing needs more than a capable robot arm. Holding, aligning, fastening and recovering require the entire system to understand and act together.",
    "challenge1Title": "Coordinate coupled tasks",
    "challenge1Desc": "Share object states and assembly relationships to synchronize handling, support and tool operation.",
    "challenge1Tag": "Joint handling · Collaborative assembly",
    "challenge2Title": "Adapt to the next task",
    "challenge2Desc": "Reuse task skills and data across product variants to reduce repeated teaching in small-batch production.",
    "challenge2Tag": "Skill reuse · Flexible changeovers",
    "challenge3Title": "Recover as a team",
    "challenge3Desc": "Account for misalignment, slipping and occlusion, then restore collaboration through observation and role reassignment.",
    "challenge3Tag": "Active observation · Recovery",
    "challenge4Title": "Connect different robots",
    "challenge4Desc": "A common interface helps accommodate differences in robot brands, control rates and latency.",
    "challenge4Tag": "Hardware adaptation · Scalability",
    "techEyebrow": "02 — THE INTELLIGENCE BEHIND THE TEAM",
    "techLine1": "One world model.",
    "techLine2": "Every arm connected.",
    "techDesc": "NCIT is developing a collaborative intelligence layer above robot hardware, closing the loop between shared understanding, joint prediction and coordinated execution.",
    "diagramAlt": "A shared world model connects four roles: feeding, alignment, fastening and adaptive support",
    "architectureTag": "System architecture",
    "diagramInput": "Multi-view observations · Object states · Task context",
    "worldModel": "Shared world model",
    "worldModelSub": "Understand · Predict · Coordinate",
    "arm1": "Feed & handle",
    "arm2": "Support & align",
    "arm3": "Connect & fasten",
    "arm4": "Adaptive support",
    "feedback": "Execution feedback and failure data improve coordination",
    "techTabs": "Technology capabilities",
    "techTab1": "Shared perception",
    "techTab2": "Joint prediction",
    "techTab3": "Adaptive recovery",
    "techTab4": "Cross-hardware adaptation",
    "platformFoot1": "Scalable collaboration, from three arms to four",
    "platformFoot2": "Connecting data, models, hardware and applications",
    "applicationEyebrow": "03 — STARTING WITH A REAL WORKCELL",
    "applicationLine1": "One frame.",
    "applicationLine2": "More ways to manufacture.",
    "applicationDesc": "Our first application is custom aluminum-frame assembly: connecting joint handling, support, alignment and fastening in a three- and four-arm collaborative system.",
    "sceneTabs": "View application environments",
    "labTab": "Physical laboratory",
    "simTab": "Simulation",
    "firstScenario": "FIRST APPLICATION / ALUMINUM-FRAME ASSEMBLY",
    "step1Title": "Feed and handle",
    "step1Desc": "Bring aluminum profiles into the shared assembly area.",
    "step2Title": "Support and align",
    "step2Desc": "Hold the frame steady and coordinate face and angle alignment.",
    "step3Title": "Connect and fasten",
    "step3Desc": "Position connectors and coordinate tool operations.",
    "step4Title": "Observe and recover",
    "step4Desc": "Respond to state changes by adapting roles and actions.",
    "applicationNote": "Start with measurable assembly tasks. Build reusable skills, data and delivery experience.",
    "directionsLabel": "APPLICATION DIRECTIONS",
    "direction1": "Wiring harness assembly",
    "direction2": "Precision inspection & loading",
    "direction3": "Flexible packaging",
    "direction4": "Large-component handling",
    "demoEyebrow": "04 — SEE COLLABORATION IN ACTION",
    "demoTitle": "Different roles. A shared goal.",
    "demoDesc": "Four robot arms, one aluminum frame. Explore how multi-arm tasks connect in our simulation demonstration.",
    "simulationBadge": "Simulation demo",
    "videoAlt": "Simulation video of four robot arms assembling an aluminum frame",
    "videoFallback": "Your browser does not support this video. Download the demonstration to watch it.",
    "videoCaption": "Four-arm collaboration · Aluminum-frame assembly · Simulation",
    "downloadVideo": "Download demo video",
    "researchTitle": "Built on continuous research",
    "researchDesc": "Connecting simulation, communication methods and real-world data to turn algorithms into systems.",
    "researchAlt1": "A simulated assembly workcell with four collaborating robot arms",
    "researchAlt2": "Sequential images of multi-arm collaboration in simulation",
    "researchAlt3": "A physical robot collecting data in a tabletop fruit-sorting task",
    "research1Title": "Shared world-model research",
    "research1Desc": "Exploring shared states, joint predictions and collaborative strategies in multi-arm simulation.",
    "research2Title": "Communication and policy learning",
    "research2Desc": "Investigating multi-arm communication and vision-language-action model training for collaborative tasks.",
    "research3Title": "Real-world data and fine-tuning",
    "research3Desc": "Collecting physical and simulated data for dual-arm household collaboration, with model fine-tuning.",
    "roadmapEyebrow": "05 — FROM RESEARCH TO DELIVERY",
    "roadmapTitle": "A clear path to the factory floor.",
    "roadmapDesc": "A 24-month development roadmap connects physical validation, model iteration, hardware adaptation and customer workcells.",
    "roadmapTime1": "MONTHS 01–03",
    "roadmapTime2": "MONTHS 04–09",
    "roadmapTime3": "MONTHS 10–15",
    "roadmapTime4": "MONTHS 16–24",
    "roadmap1Title": "Three-arm proof of concept",
    "roadmap1Desc": "Validate a scoped physical workflow for handling, holding, alignment and connection, with a unified data interface.",
    "roadmap2Title": "Shared world model V1",
    "roadmap2Desc": "Build object and assembly states, exception logs and joint-action predictions, with baseline comparisons.",
    "roadmap3Title": "Four arms, broader hardware",
    "roadmap3Desc": "Extend joint handling, support and tool operations to four arms and integrate a second robot interface.",
    "roadmap4Title": "Customer validation and replication",
    "roadmap4Desc": "Advance edge deployment, continuous operation and acceptance testing, then replicate at a second workcell.",
    "targetsLabel": "DEVELOPMENT TARGETS",
    "targetsNote": "24-month roadmap",
    "target1": "Coordinated robot arms",
    "target2": "Robot interface types",
    "target3": "Continuous operation",
    "target4": "Paid PoCs or orders",
    "teamEyebrow": "06 — RESEARCH MEETS INDUSTRY",
    "teamLine1": "Shared ambition.",
    "teamLine2": "Complementary strengths.",
    "teamDesc": "Bringing together multi-agent research, technology commercialization and robotic systems engineering to connect scientific progress with delivery.",
    "name1": "Ningxin Su",
    "name2": "Shuaijun Liu",
    "name3": "Qingkai Yang",
    "role1": "Project Lead · Chief Scientist",
    "role2": "Proposed CEO · Product & Business",
    "role3": "Engineering & Delivery Lead",
    "bio1": "Assistant Professor jointly appointed in IoT and Robotics at HKUST(GZ), with a PhD from the University of Toronto. Leads multi-agent world-model research and R&D.",
    "bio2": "Doctoral researcher and entrepreneur, co-founder of ayaMaa with experience in international brand operations. Leads productization, customer discovery and business operations.",
    "bio3": "CEO of Ruidong Xinchuang and former core engineer for Leju’s Kuavo series, with humanoid and heavy-duty quadruped development experience. Leads hardware, systems and field delivery.",
    "expertise1": "Multi-agent algorithms / Industry–academia R&D",
    "expertise2": "Productization / Customers & operations",
    "expertise3": "Robotic systems / Engineering delivery",
    "collabEyebrow": "07 — BRINGING CAPABILITY INTO PRODUCTION",
    "collabTitle": "Bring collaboration to your workcell.",
    "collabDesc": "We partner with manufacturers, robot makers and system integrators, contributing the collaborative intelligence layer from task definition to deployment and replication.",
    "cooperation1Title": "Co-design and paid PoCs",
    "cooperation1Desc": "Define materials, processes and collaboration needs. Agree on task boundaries and acceptance criteria, then validate a minimum viable workflow.",
    "cooperation2Title": "Workcell deployment",
    "cooperation2Desc": "Adapt algorithms and interfaces, train models, run regression checks and validate performance at the actual workcell.",
    "cooperation3Title": "Ongoing service and scale",
    "cooperation3Desc": "Reuse data and skills through annual licensing, upgrades, task packages and OEM partnerships to support additional workcells.",
    "contactEyebrow": "LET’S BUILD TOGETHER",
    "contactLine1": "Your next collaboration",
    "contactLine2": "starts here.",
    "contactDesc": "Have a manufacturing challenge that takes more than one pair of robotic hands? Let’s explore it together.",
    "contactLabel": "PROJECT & RESEARCH COLLABORATION",
    "contactPerson": "Ningxin Su · Project Lead",
    "emailUs": "Get in touch",
    "visitLab": "Discover NEBULIS Lab",
    "footerBrand": "Collaborative Intelligence · NCIT",
    "footerMission": "Many arms. One shared intelligence.",
    "footerStatus": "A technology startup project from HKUST(GZ) · Planned in Nansha, Guangzhou",
    "backTop": "Back to top"
  }
};

const NCIT_FEATURES = {
  zh: [
    { kicker: 'SHARED UNDERSTANDING', title: '看到不同视角，理解同一个现场。', description: '将多机械臂的观测、对象姿态与装配关系组织为共享状态，为任务分工与协作决策提供共同依据。' },
    { kicker: 'JOINT ACTION PREDICTION', title: '预测彼此的动作，协调下一步。', description: '结合对象约束与任务上下文，预测多机械臂联合动作的影响，让共同持物、对齐和紧固在同一协作计划中衔接。' },
    { kicker: 'CONTEXT-AWARE RECOVERY', title: '当现场变化，协作随之调整。', description: '围绕滑移、错位和遮挡建立异常状态与反馈。通过主动观察、动作调整和任务接替，学习与当前情境匹配的恢复策略。' },
    { kicker: 'CROSS-HARDWARE ADAPTATION', title: '把协作能力，带到不同机械臂。', description: '通过统一动作与状态接口适配不同机械臂的控制频率、精度和时延。首期规划接入 2—3 类接口，以型号回归验证支持后续工位复制。' }
  ],
  en: [
    { kicker: 'SHARED UNDERSTANDING', title: 'Different viewpoints. The same understanding.', description: 'Combine observations, object poses and assembly relationships into a shared state that grounds role allocation and collaborative decisions.' },
    { kicker: 'JOINT ACTION PREDICTION', title: 'Anticipate each other. Coordinate what comes next.', description: 'Use object constraints and task context to predict the effects of joint actions, linking holding, alignment and fastening within one collaborative plan.' },
    { kicker: 'CONTEXT-AWARE RECOVERY', title: 'When conditions change, the team adapts.', description: 'Track slipping, misalignment and occlusion through state feedback. Learn context-dependent recovery with active observation, action correction and role reassignment.' },
    { kicker: 'CROSS-HARDWARE ADAPTATION', title: 'Bring collaborative skills to different robots.', description: 'A common action and state interface accommodates control rates, precision and latency. The initial roadmap targets 2–3 interface types, supported by hardware-specific regression checks.' }
  ]
};
const NCIT_SCENES = {
  lab: { image: 'assets/images/lab-assembly.webp', zh: { alt: '团队实验室中机械臂与铝型材框架的真实实验装置', caption: '团队实验室 · 铝型材协作组装实验环境' }, en: { alt: 'Physical robot arms and an aluminum frame in the team’s laboratory', caption: 'Team laboratory · Aluminum-frame assembly setup' } },
  sim: { image: 'assets/images/simulation-workcell.webp', zh: { alt: '四只机械臂围绕铝型材框架的仿真装配工位', caption: '模拟环境 · 四臂协作工位与装配布局' }, en: { alt: 'A simulated assembly workcell with four robot arms around an aluminum frame', caption: 'Simulation · Four-arm workcell and assembly layout' } }
};
