const content = {
  zh: {
    companyName: '广州星云协智科技有限公司',
    companyNameEn: 'Guangzhou Nebulis Collaborative Intelligence Technology Co., Ltd.',
    companyShort: '星云协智',
    institutionLabel: '科研起点',
    universityName: '香港科技大学（广州）',
    navPartnership: '合作路径',
    challengeLabel: '面向非标制造',
    challengeHeading: '复杂的协作，需要共同的理解。',
    challengeIntro: '多品种、小批量的工位中，搬运、支撑与工具作业紧密相连。我们从这些真实的协作需求出发。',
    challenge1Title: '共同持物，协调每一步',
    challenge1Desc: '从支撑、对齐到紧固，多只机械臂需要共享对象状态、明确任务分工，并保持动作时序一致。',
    challenge1Tag: '强耦合任务',
    challenge2Title: '面对变化，重新组织协作',
    challenge2Desc: '围绕工件规格、装配关系和工艺变化，研究可重配置的任务技能与跨本体适配，让能力在不同工位复用。',
    challenge2Tag: '柔性换型',
    challenge3Title: '遇到异常，继续完成任务',
    challenge3Desc: '将错位、遮挡和抓取滑移纳入状态理解，通过主动观察、调整分工与任务接替研究协作恢复。',
    challenge3Tag: '协作恢复',
    partnershipLabel: '与产业伙伴同行',
    partnershipHeading: '从一个具体任务，开始合作。',
    partnershipIntro: '面向制造企业、机械臂厂商与系统集成商，提供协同智能层，连接现有设备、工艺与生产需求。',
    partnership1Title: '定义工位',
    partnership1Desc: '梳理物料、工序和设备条件，共同确认最值得验证的协作任务。',
    partnership2Title: '概念验证',
    partnership2Desc: '约定成功率、节拍与人工干预等验收条件，建立最小协作闭环。',
    partnership3Title: '部署验证',
    partnership3Desc: '推进接口适配、模型优化和现场联调，验证连续作业表现。',
    partnership4Title: '复制与迭代',
    partnership4Desc: '沉淀任务技能、失败数据与回归集，支持下一工位的部署和持续优化。',
    partnershipCta: '讨论你的工位需求',
    partnershipNote: '合作从明确的任务范围与共同认可的验收标准开始。',
  },
  en: {
    companyName: 'Guangzhou Nebulis Collaborative Intelligence Technology Co., Ltd.',
    companyNameEn: 'Guangzhou Nebulis Collaborative Intelligence Technology Co., Ltd.',
    companyShort: 'Nebulis Collaborative Intelligence Technology',
    institutionLabel: 'Our research roots',
    universityName: 'The Hong Kong University of Science and Technology (Guangzhou)',
    navPartnership: 'Partnerships',
    challengeLabel: 'Built for flexible manufacturing',
    challengeHeading: 'Complex collaboration starts with shared understanding.',
    challengeIntro: 'In high-mix, low-volume workcells, transport, support and tool use depend on each other. These real coordination needs guide our work.',
    challenge1Title: 'Handle together. Coordinate every move.',
    challenge1Desc: 'From support and alignment to fastening, arms need a shared object state, clear roles and consistent timing.',
    challenge1Tag: 'Coupled tasks',
    challenge2Title: 'Adapt the collaboration to the task.',
    challenge2Desc: 'Develop reconfigurable skills and hardware adaptation around changes in parts, assembly relationships and processes, so capabilities can transfer between workcells.',
    challenge2Tag: 'Flexible changeovers',
    challenge3Title: 'Recover together when conditions change.',
    challenge3Desc: 'Account for misalignment, occlusion and slipping. Explore recovery through active observation, role adjustment and task handover.',
    challenge3Tag: 'Collaborative recovery',
    partnershipLabel: 'Working with industry',
    partnershipHeading: 'Start with one concrete task.',
    partnershipIntro: 'An intelligence layer for manufacturers, robot makers and system integrators, connecting existing equipment, processes and production needs.',
    partnership1Title: 'Define the workcell',
    partnership1Desc: 'Review materials, processes and equipment together to identify the collaboration task worth validating.',
    partnership2Title: 'Prove the workflow',
    partnership2Desc: 'Agree on success rate, cycle time and human intervention criteria, then establish the first complete workflow.',
    partnership3Title: 'Validate on site',
    partnership3Desc: 'Integrate interfaces, refine models and commission the system to assess continuous operation.',
    partnership4Title: 'Replicate and improve',
    partnership4Desc: 'Build reusable skills, failure data and regression sets to support the next workcell and ongoing improvements.',
    partnershipCta: 'Discuss your workcell',
    partnershipNote: 'Every collaboration starts with a defined task and shared acceptance criteria.',
  },
};
export default content;
