const vlaCopy = {
  zh: {
    heroIntro: '以共享世界模型理解环境，以多臂协作 VLA 连接观测、指令与动作。面向柔性制造，让多只机械臂理解同一个世界，协同完成复杂任务。',
    techLabel: '共享世界模型 × 多臂协作 VLA',
    techHeading: '共同理解环境，协同生成动作。',
    techIntro: '我们以共享世界模型研究环境与任务状态，以分布式视觉—语言—动作（VLA）策略组织多臂执行，连接预测、通信与协同行动。',
    techC: '多臂协作 VLA',
    techCd: '每只机械臂保有自己的观测与动作输出，通过策略间通信协调搬运、支撑与工具作业。',
    techE: '可扩展的智能体网络',
    techEd: '以一臂一智能体组织团队，通过增添协作节点扩展臂数，并研究不同本体的接口适配。',
    flow3Title: '协同 VLA 与数据',
    flow3Desc: '结合多臂 VLA 仿真研究与真机数据采集，迭代通信、策略和协作技能。',
    diagramAlt: '共享世界模型与多臂协作 VLA 的系统路线示意',
    diagramPolicy: '多臂协作 VLA · 一臂一智能体',
    diagramCommunication: '状态同步 · 跨臂信息 · 动作意图',
    vlaLabel: '已有研究基础',
    vlaHeading: '让每只机械臂独立决策，让通信组织协作。',
    vlaIntro: '视觉—语言—动作（VLA）模型将图像、任务指令和机器人状态转化为动作。我们的多臂方案让每只机械臂运行独立策略，通过显式的信息交换，组成能够协作的智能体团队。',
    vla1Title: '共享任务状态',
    vla1Desc: '同步共同的任务表征，让不同机械臂围绕同一个目标理解协作进程。',
    vla2Title: '交换跨臂上下文',
    vla2Desc: '在策略推理过程中交换其他机械臂的观测表征，补充本地视角的信息。',
    vla3Title: '协调动作意图',
    vla3Desc: '在生成动作前交换下一步的行动意图，让独立动作衔接为共同作业。',
    vlaScale: '智能体仿真任务',
    vlaScaleDetail: '覆盖双臂交接、三臂协作与四臂任务。',
    vlaTraffic: '双向通信量降低',
    vlaTrafficDetail: '在 2–4 智能体配对仿真评估中，8 层通信配置相较原始通信实现（Raw）的降幅。',
  },
  en: {
    heroIntro: 'Understand the environment through a shared world model. Connect observations, instructions and actions with collaborative multi-arm VLA policies, bringing coordinated intelligence to flexible manufacturing.',
    techLabel: 'Shared world model × Multi-arm VLA',
    techHeading: 'Understand together. Act in coordination.',
    techIntro: 'We study environment and task states through a shared world model, and organize execution with distributed vision-language-action (VLA) policies, connecting prediction, communication and coordinated action.',
    techC: 'Collaborative multi-arm VLA',
    techCd: 'Each arm owns its observations and action output, coordinating transport, support and tool use through communication between policies.',
    techE: 'Scalable agent networks',
    techEd: 'Organize one agent per arm, extend the team with additional cooperating agents, and study interfaces for different robot hardware.',
    flow3Title: 'Collaborative VLA and data',
    flow3Desc: 'Connect multi-arm VLA simulation research with real-world data collection to improve communication, policies and skills.',
    diagramAlt: 'System direction connecting a shared world model with collaborative multi-arm VLA agents',
    diagramPolicy: 'Multi-arm VLA · One agent per arm',
    diagramCommunication: 'State synchronization · Cross-arm context · Action intent',
    roleA: 'Move',
    roleB: 'Hold',
    vlaLabel: 'Research foundation',
    vlaHeading: 'Independent policies. Coordinated through communication.',
    vlaIntro: 'Vision-language-action (VLA) models turn images, task instructions and robot states into actions. Our multi-arm approach gives each arm an independent policy and connects them through explicit information exchange.',
    vla1Title: 'Shared task state',
    vla1Desc: 'Synchronize common task representations so every arm interprets progress toward the same goal.',
    vla2Title: 'Cross-arm context',
    vla2Desc: 'Exchange other arms’ observation representations during policy inference to complement each local view.',
    vla3Title: 'Action intent',
    vla3Desc: 'Share imminent action intent before decoding, connecting independently generated actions into joint work.',
    vlaScale: 'Agents in simulation tasks',
    vlaScaleDetail: 'Bimanual handovers and collaborative tasks with three and four agents.',
    vlaTraffic: 'Less bidirectional traffic',
    vlaTrafficDetail: 'Reduction versus the original Raw interface using an eight-layer communication profile in paired two- to four-agent simulation evaluations.',
  },
};
export default vlaCopy;
